package asserts

import _ "embed"

var (
	//go:embed 1.jpg
	Buf1 []byte
	//go:embed 2.jpg
	Buf2 []byte
	//go:embed 3.jpg
	Buf3 []byte
	//go:embed 4.png
	Buf4 []byte
	//go:embed 5.jpeg
	Buf5 []byte
	//go:embed 6.png
	Buf6 []byte
	//go:embed 7.jpeg
	Buf7 []byte
	//go:embed 8.png
	Buf8 []byte
	//go:embed 9.jpg
	Buf9 []byte
	//go:embed 10.png
	Buf10 []byte
	//go:embed 11.png
	Buf11 []byte
	//go:embed 12.jpeg
	Buf12 []byte
	//go:embed 13.jpeg
	Buf13 []byte
	//go:embed 14.png
	Buf14 []byte
	//go:embed 15.png
	Buf15 []byte
	//go:embed 16.png
	Buf16 []byte
	//go:embed 17.jpg
	Buf17 []byte
	//go:embed 18.jpg
	Buf18 []byte
	//go:embed 19.jpg
	Buf19 []byte
	//go:embed 20.png
	Buf20 []byte
	//go:embed 21.ico
	Buf21 []byte
	//go:embed 22.jpeg
	Buf22 []byte
	//go:embed mitm.ico
	MitmBuf []byte
	//go:embed open.ico
	BufOpen []byte
	//go:embed about.jpg
	BufAbout []byte
)
